fail_fast: true
repos:
  - repo: local
    hooks:
      - id: luacheck
        name: luacheck
        entry: ./tools/luacheck.sh
        language: script
        files: \.lua$
      - id: lua-fmt
        name: lua-fmt
        entry: ./tools/format.sh
        language: script
        files: \.lua$
